stages:
  - build
  - test
  - deploy
  - revert

variables:
  DOCKER_HTML_PATH: "/www"
  ENV: prod
  DEPLOY_SUBFOLDER: html

install_dependencies:
  image: node:14.15.0-stretch
  stage: build
  script:
    - yarn install
    - yarn build
    - mv build build_$ENV
  artifacts:
    paths:
      - node_modules
      - build_$ENV
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules

build_staging:
  extends: install_dependencies
  variables:
    ENV: staging
    REACT_APP_WEBSITE_PREFIX: "[staging]"
    PUBLIC_URL: "/$CI_COMMIT_BRANCH"

deploy_staging:
  extends: deploy_prod
  variables:
    DEPLOY_SUBFOLDER: staging/$CI_COMMIT_BRANCH
    ENV: staging
  when: always
  only:
    - master
    - /feature-.*/

deploy_prod:
  stage: deploy
  script:
    - mkdir $DOCKER_HTML_PATH/$ENV/$CI_COMMIT_BRANCH
    - cp -r build_$ENV $DOCKER_HTML_PATH/test-app/${ENV}_$CI_COMMIT_SHA
    - cp -Pv $DOCKER_HTML_PATH/$DEPLOY_SUBFOLDER $DOCKER_HTML_PATH/test-app/${ENV}_$CI_COMMIT_SHA/prev-version || true
  only:
    - master

activate_staging:
  extends: activate_prod
  variables:
    DEPLOY_SUBFOLDER: staging/$CI_COMMIT_BRANCH
    ENV: staging
  when: always
  only:
    - master
    - /feature-.*/

activate_prod:
  stage: deploy
  script:
    - ln -fsnv /var/www/test-app/${ENV}_$CI_COMMIT_SHA $DOCKER_HTML_PATH/$DEPLOY_SUBFOLDER
  when: manual
  only:
    - master

revert:
  stage: revert
  when: manual
  script:
    - cp -Pv --remove-destination $DOCKER_HTML_PATH/test-app/$CI_COMMIT_SHA/prev-version $DOCKER_HTML_PATH/html


